name: Vidmap
version: 0.0.1
main: academy.hekiyou.vidmap.VidmapPlugin
description: Playback videos on Minecraft maps
api-version: '1.21.11'

commands:
  vidmap:
    description: Root command for this plugin